// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_datetime`, `parse_datetime`, `to_err_string`, `with_db`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`, `try_from`, `try_from`, `try_from`

Future<bool> dbIsInitialized() =>
    RustLib.instance.api.crateApiDbDbIsInitialized();

Future<FrbDbInfo> dbInit({required String dbPath}) =>
    RustLib.instance.api.crateApiDbDbInit(dbPath: dbPath);

Future<void> dbUpsertConversation({required FrbConversation conversation}) =>
    RustLib.instance.api.crateApiDbDbUpsertConversation(
      conversation: conversation,
    );

Future<void> dbUpsertMessage({required FrbMessage message}) =>
    RustLib.instance.api.crateApiDbDbUpsertMessage(message: message);

Future<void> dbUpsertToolEvent({required FrbToolEvent event}) =>
    RustLib.instance.api.crateApiDbDbUpsertToolEvent(event: event);

Future<FrbConversation?> dbQueryConversation({required String id}) =>
    RustLib.instance.api.crateApiDbDbQueryConversation(id: id);

Future<List<FrbMessage>> dbQueryMessages({
  required String conversationId,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiDbDbQueryMessages(
  conversationId: conversationId,
  limit: limit,
  offset: offset,
);

Future<List<FrbToolEvent>> dbQueryToolEvents({required String messageId}) =>
    RustLib.instance.api.crateApiDbDbQueryToolEvents(messageId: messageId);

Future<void> dbDeleteConversation({required String id}) =>
    RustLib.instance.api.crateApiDbDbDeleteConversation(id: id);

Future<FrbDbSnapshot> dbExportSnapshot() =>
    RustLib.instance.api.crateApiDbDbExportSnapshot();

Future<FrbImportSummary> dbImportSnapshot({required FrbDbSnapshot snapshot}) =>
    RustLib.instance.api.crateApiDbDbImportSnapshot(snapshot: snapshot);

class FrbConversation {
  final String id;
  final String title;
  final String createdAt;
  final String updatedAt;
  final List<String> messageIds;
  final bool isPinned;
  final List<String> mcpServerIds;
  final String? assistantId;
  final int truncateIndex;
  final Map<String, int> versionSelections;

  const FrbConversation({
    required this.id,
    required this.title,
    required this.createdAt,
    required this.updatedAt,
    required this.messageIds,
    required this.isPinned,
    required this.mcpServerIds,
    this.assistantId,
    required this.truncateIndex,
    required this.versionSelections,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      messageIds.hashCode ^
      isPinned.hashCode ^
      mcpServerIds.hashCode ^
      assistantId.hashCode ^
      truncateIndex.hashCode ^
      versionSelections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbConversation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          messageIds == other.messageIds &&
          isPinned == other.isPinned &&
          mcpServerIds == other.mcpServerIds &&
          assistantId == other.assistantId &&
          truncateIndex == other.truncateIndex &&
          versionSelections == other.versionSelections;
}

class FrbDbInfo {
  final String path;
  final int appliedMigrations;
  final int version;

  const FrbDbInfo({
    required this.path,
    required this.appliedMigrations,
    required this.version,
  });

  @override
  int get hashCode =>
      path.hashCode ^ appliedMigrations.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbDbInfo &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          appliedMigrations == other.appliedMigrations &&
          version == other.version;
}

class FrbDbSnapshot {
  final List<FrbConversation> conversations;
  final List<FrbMessage> messages;
  final List<FrbToolEvent> toolEvents;

  const FrbDbSnapshot({
    required this.conversations,
    required this.messages,
    required this.toolEvents,
  });

  @override
  int get hashCode =>
      conversations.hashCode ^ messages.hashCode ^ toolEvents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbDbSnapshot &&
          runtimeType == other.runtimeType &&
          conversations == other.conversations &&
          messages == other.messages &&
          toolEvents == other.toolEvents;
}

class FrbImportSummary {
  final int conversations;
  final int messages;
  final int toolEvents;

  const FrbImportSummary({
    required this.conversations,
    required this.messages,
    required this.toolEvents,
  });

  @override
  int get hashCode =>
      conversations.hashCode ^ messages.hashCode ^ toolEvents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbImportSummary &&
          runtimeType == other.runtimeType &&
          conversations == other.conversations &&
          messages == other.messages &&
          toolEvents == other.toolEvents;
}

class FrbMessage {
  final String id;
  final String conversationId;
  final String role;
  final String content;
  final String timestamp;
  final String? modelId;
  final String? providerId;
  final int? totalTokens;
  final bool isStreaming;
  final String? reasoningText;
  final String? reasoningStartAt;
  final String? reasoningFinishedAt;
  final String? translation;
  final String? reasoningSegmentsJson;
  final String? groupId;
  final int version;

  const FrbMessage({
    required this.id,
    required this.conversationId,
    required this.role,
    required this.content,
    required this.timestamp,
    this.modelId,
    this.providerId,
    this.totalTokens,
    required this.isStreaming,
    this.reasoningText,
    this.reasoningStartAt,
    this.reasoningFinishedAt,
    this.translation,
    this.reasoningSegmentsJson,
    this.groupId,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      timestamp.hashCode ^
      modelId.hashCode ^
      providerId.hashCode ^
      totalTokens.hashCode ^
      isStreaming.hashCode ^
      reasoningText.hashCode ^
      reasoningStartAt.hashCode ^
      reasoningFinishedAt.hashCode ^
      translation.hashCode ^
      reasoningSegmentsJson.hashCode ^
      groupId.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          role == other.role &&
          content == other.content &&
          timestamp == other.timestamp &&
          modelId == other.modelId &&
          providerId == other.providerId &&
          totalTokens == other.totalTokens &&
          isStreaming == other.isStreaming &&
          reasoningText == other.reasoningText &&
          reasoningStartAt == other.reasoningStartAt &&
          reasoningFinishedAt == other.reasoningFinishedAt &&
          translation == other.translation &&
          reasoningSegmentsJson == other.reasoningSegmentsJson &&
          groupId == other.groupId &&
          version == other.version;
}

class FrbToolEvent {
  final String id;
  final String messageId;
  final String name;
  final String payload;
  final String createdAt;

  const FrbToolEvent({
    required this.id,
    required this.messageId,
    required this.name,
    required this.payload,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      messageId.hashCode ^
      name.hashCode ^
      payload.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbToolEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          messageId == other.messageId &&
          name == other.name &&
          payload == other.payload &&
          createdAt == other.createdAt;
}
