// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_docx_xml`

Future<String> extractTextFromPdf({required String path}) =>
    RustLib.instance.api.crateApiDocumentParserExtractTextFromPdf(path: path);

Future<String> extractTextFromDocx({required String path}) =>
    RustLib.instance.api.crateApiDocumentParserExtractTextFromDocx(path: path);

Future<String> readTextFallback({required String path}) =>
    RustLib.instance.api.crateApiDocumentParserReadTextFallback(path: path);
