// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'llm_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `llm_service`, `stream_error_to_string`

Future<FrbChatResponse> llmChat({required FrbChatRequest request}) =>
    RustLib.instance.api.crateApiLlmLlmChat(request: request);

Stream<String> llmChatStream({required FrbChatRequest request}) =>
    RustLib.instance.api.crateApiLlmLlmChatStream(request: request);

Future<bool> llmCancel({required String requestId}) =>
    RustLib.instance.api.crateApiLlmLlmCancel(requestId: requestId);
