// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FrbChatDelta`, `FrbChatEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class FrbChatMessage {
  final FrbChatRole role;
  final List<String> parts;

  const FrbChatMessage({required this.role, required this.parts});

  @override
  int get hashCode => role.hashCode ^ parts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbChatMessage &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          parts == other.parts;
}

class FrbChatRequest {
  final String requestId;
  final String? provider;
  final String model;
  final List<FrbChatMessage> messages;
  final double? temperature;
  final double? topP;
  final int? maxOutputTokens;
  final Map<String, String> metadata;

  const FrbChatRequest({
    required this.requestId,
    this.provider,
    required this.model,
    required this.messages,
    this.temperature,
    this.topP,
    this.maxOutputTokens,
    required this.metadata,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      messages.hashCode ^
      temperature.hashCode ^
      topP.hashCode ^
      maxOutputTokens.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbChatRequest &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          provider == other.provider &&
          model == other.model &&
          messages == other.messages &&
          temperature == other.temperature &&
          topP == other.topP &&
          maxOutputTokens == other.maxOutputTokens &&
          metadata == other.metadata;
}

class FrbChatResponse {
  final String requestId;
  final String providerId;
  final String model;
  final String outputText;
  final FrbChatUsage usage;

  const FrbChatResponse({
    required this.requestId,
    required this.providerId,
    required this.model,
    required this.outputText,
    required this.usage,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      providerId.hashCode ^
      model.hashCode ^
      outputText.hashCode ^
      usage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbChatResponse &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          providerId == other.providerId &&
          model == other.model &&
          outputText == other.outputText &&
          usage == other.usage;
}

enum FrbChatRole { user, assistant, system, tool }

class FrbChatUsage {
  final int promptTokens;
  final int completionTokens;
  final int totalTokens;

  const FrbChatUsage({
    required this.promptTokens,
    required this.completionTokens,
    required this.totalTokens,
  });

  @override
  int get hashCode =>
      promptTokens.hashCode ^ completionTokens.hashCode ^ totalTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbChatUsage &&
          runtimeType == other.runtimeType &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens;
}
